apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: timemachine-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/trajkovicd/timemachine-operator-index:v1.0.6
  displayName: Time Machine Operator
  publisher: Red Hat Partner
  updateStrategy:
    registryPoll:
      interval: 5m
