apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: timemachine-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Time Machine creates virtual clocks for time shift testing of applications
  displayName: Time Machine Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - time shift
  - time travel
  - virtual clocks
  - time machine
  - testing
  links:
  - name: Timemachine Operator
    url: https://timemachine-operator.domain
  maintainers:
  - email: dtrajkovic@solution-soft.com
    name: Dragan Trajkovic
  maturity: alpha
  provider:
    name: Solution-Soft
    url: solution-soft.com
  version: 0.0.0
